//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HcpServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://operations.ptt.gov.tr")]
    public partial class FileOperationsException
    {
        
        private Exception fileOperationsException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FileOperationsException", IsNullable=true, Order=0)]
        public Exception FileOperationsException1
        {
            get
            {
                return this.fileOperationsException1Field;
            }
            set
            {
                this.fileOperationsException1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.ptt.gov.tr")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.ptt.gov.tr/xsd")]
    public partial class OutputDownloadHcp
    {
        
        private byte[] byteFileField;
        
        private string hataAciklamaField;
        
        private int hataKodField;
        
        private bool hataKodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] byteFile
        {
            get
            {
                return this.byteFileField;
            }
            set
            {
                this.byteFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int hataKod
        {
            get
            {
                return this.hataKodField;
            }
            set
            {
                this.hataKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hataKodSpecified
        {
            get
            {
                return this.hataKodFieldSpecified;
            }
            set
            {
                this.hataKodFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://operations.ptt.gov.tr", ConfigurationName="HcpServiceReference.FileOperationsPortType")]
    public interface FileOperationsPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileDownload", ReplyAction="urn:fileDownloadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HcpServiceReference.FileOperationsException), Action="urn:fileDownloadFileOperationsException", Name="FileOperationsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HcpServiceReference.fileDownloadResponse> fileDownloadAsync(HcpServiceReference.fileDownloadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileDelete", ReplyAction="urn:fileDeleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HcpServiceReference.FileOperationsException), Action="urn:fileDeleteFileOperationsException", Name="FileOperationsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HcpServiceReference.fileDeleteResponse> fileDeleteAsync(HcpServiceReference.fileDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fileUpload", ReplyAction="urn:fileUploadResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HcpServiceReference.FileOperationsException), Action="urn:fileUploadFileOperationsException", Name="FileOperationsException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<HcpServiceReference.fileUploadResponse> fileUploadAsync(HcpServiceReference.fileUploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileDownload", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileDownloadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dosyaAdi;
        
        public fileDownloadRequest()
        {
        }
        
        public fileDownloadRequest(string userName, string password, string dosyaAdi)
        {
            this.userName = userName;
            this.password = password;
            this.dosyaAdi = dosyaAdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileDownloadResponse", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileDownloadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public HcpServiceReference.OutputDownloadHcp @return;
        
        public fileDownloadResponse()
        {
        }
        
        public fileDownloadResponse(HcpServiceReference.OutputDownloadHcp @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://operations.ptt.gov.tr/xsd")]
    public partial class OutputHcp
    {
        
        private byte[] byteFileField;
        
        private string dosyaPathField;
        
        private string fileLocationField;
        
        private string hashKodField;
        
        private string hataAciklamaField;
        
        private int hataKodField;
        
        private bool hataKodFieldSpecified;
        
        private int httpCodeField;
        
        private bool httpCodeFieldSpecified;
        
        private string versionIdField;
        
        private string yeniDosyaAdiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] byteFile
        {
            get
            {
                return this.byteFileField;
            }
            set
            {
                this.byteFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dosyaPath
        {
            get
            {
                return this.dosyaPathField;
            }
            set
            {
                this.dosyaPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string fileLocation
        {
            get
            {
                return this.fileLocationField;
            }
            set
            {
                this.fileLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string hashKod
        {
            get
            {
                return this.hashKodField;
            }
            set
            {
                this.hashKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int hataKod
        {
            get
            {
                return this.hataKodField;
            }
            set
            {
                this.hataKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hataKodSpecified
        {
            get
            {
                return this.hataKodFieldSpecified;
            }
            set
            {
                this.hataKodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int httpCode
        {
            get
            {
                return this.httpCodeField;
            }
            set
            {
                this.httpCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool httpCodeSpecified
        {
            get
            {
                return this.httpCodeFieldSpecified;
            }
            set
            {
                this.httpCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string versionId
        {
            get
            {
                return this.versionIdField;
            }
            set
            {
                this.versionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string yeniDosyaAdi
        {
            get
            {
                return this.yeniDosyaAdiField;
            }
            set
            {
                this.yeniDosyaAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileDelete", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileDeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dosyaAdi;
        
        public fileDeleteRequest()
        {
        }
        
        public fileDeleteRequest(string userName, string password, string dosyaAdi)
        {
            this.userName = userName;
            this.password = password;
            this.dosyaAdi = dosyaAdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileDeleteResponse", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileDeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public HcpServiceReference.OutputHcp @return;
        
        public fileDeleteResponse()
        {
        }
        
        public fileDeleteResponse(HcpServiceReference.OutputHcp @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileUpload", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileUploadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] dosyaByte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dosyaAdi;
        
        public fileUploadRequest()
        {
        }
        
        public fileUploadRequest(string userName, string password, byte[] dosyaByte, string dosyaAdi)
        {
            this.userName = userName;
            this.password = password;
            this.dosyaByte = dosyaByte;
            this.dosyaAdi = dosyaAdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileUploadResponse", WrapperNamespace="http://operations.ptt.gov.tr", IsWrapped=true)]
    public partial class fileUploadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://operations.ptt.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public HcpServiceReference.OutputHcp @return;
        
        public fileUploadResponse()
        {
        }
        
        public fileUploadResponse(HcpServiceReference.OutputHcp @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface FileOperationsPortTypeChannel : HcpServiceReference.FileOperationsPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class FileOperationsPortTypeClient : System.ServiceModel.ClientBase<HcpServiceReference.FileOperationsPortType>, HcpServiceReference.FileOperationsPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FileOperationsPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(FileOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), FileOperationsPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileOperationsPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FileOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileOperationsPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FileOperationsPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FileOperationsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HcpServiceReference.fileDownloadResponse> HcpServiceReference.FileOperationsPortType.fileDownloadAsync(HcpServiceReference.fileDownloadRequest request)
        {
            return base.Channel.fileDownloadAsync(request);
        }
        
        public System.Threading.Tasks.Task<HcpServiceReference.fileDownloadResponse> fileDownloadAsync(string userName, string password, string dosyaAdi)
        {
            HcpServiceReference.fileDownloadRequest inValue = new HcpServiceReference.fileDownloadRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.dosyaAdi = dosyaAdi;
            return ((HcpServiceReference.FileOperationsPortType)(this)).fileDownloadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HcpServiceReference.fileDeleteResponse> HcpServiceReference.FileOperationsPortType.fileDeleteAsync(HcpServiceReference.fileDeleteRequest request)
        {
            return base.Channel.fileDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<HcpServiceReference.fileDeleteResponse> fileDeleteAsync(string userName, string password, string dosyaAdi)
        {
            HcpServiceReference.fileDeleteRequest inValue = new HcpServiceReference.fileDeleteRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.dosyaAdi = dosyaAdi;
            return ((HcpServiceReference.FileOperationsPortType)(this)).fileDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HcpServiceReference.fileUploadResponse> HcpServiceReference.FileOperationsPortType.fileUploadAsync(HcpServiceReference.fileUploadRequest request)
        {
            return base.Channel.fileUploadAsync(request);
        }
        
        public System.Threading.Tasks.Task<HcpServiceReference.fileUploadResponse> fileUploadAsync(string userName, string password, byte[] dosyaByte, string dosyaAdi)
        {
            HcpServiceReference.fileUploadRequest inValue = new HcpServiceReference.fileUploadRequest();
            inValue.userName = userName;
            inValue.password = password;
            inValue.dosyaByte = dosyaByte;
            inValue.dosyaAdi = dosyaAdi;
            return ((HcpServiceReference.FileOperationsPortType)(this)).fileUploadAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileOperationsHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.FileOperationsHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FileOperationsHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://postaapp1.ptt.gov.tr/HCPService/services/FileOperations.FileOperationsHttp" +
                        "Soap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.FileOperationsHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://postaapp1.ptt.gov.tr/HCPService/services/FileOperations.FileOperationsHttp" +
                        "Soap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            FileOperationsHttpSoap11Endpoint,
            
            FileOperationsHttpSoap12Endpoint,
        }
    }
}
